# These are supported funding model platforms

#github: [iranika] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://www.paypal.me/iranika', 'https://iranika.github.io/'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
ko_fi: iranika # Replace with a single Ko-fi username
