# These are supported funding model platforms

github: [iranika] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: [iranika] # Replace with a single Patreon username
open_collective: iranika # Replace with a single Open Collective username
ko_fi: iranika # Replace with a single Ko-fi username
tidelift: iranika/mo-code # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: mo-code # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: iranika # Replace with a single Liberapay username
issuehunt: iranika # Replace with a single IssueHunt username
otechie: iranika # Replace with a single Otechie username
custom: ['https://iranika.github.io/'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
