name: Update check

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-1.0.4
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-1.0.4
    - name: Install Nim & mosq build
      if: steps.cache-choosenim.outputs.cache-hit != 'true' || steps.cache-nimble.outputs.cache-hit != 'true'
      run: |
        export CHOOSENIM_CHOOSE_VERSION="1.0.4"
        curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        sh init.sh -y
    - uses: actions/checkout@v2
    - name: initialize git setting.
      run: |
        git config --global user.name "iranika"
        git config --global user.email "7370486+iranika@users.noreply.github.com"
        git remote set-url origin https://iranika:${GITHUB_TOKEN}@github.com/iranika/mo-code.git
        git fetch
        git checkout refactor/selfhost
    - name: check update momoirocode 
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        cd mosq
        nimble build -y -d:release
        cd ..
        ./mosq/bin/mosq | grep -v "No updates" && \
        (git add 4koma/* 4komaData.js 4komaData.js.org feed.atom update-info.dat && \
        git commit -m "update: auto updated 4komaData by yurika" && \
        git push origin refactor/selfhost) || echo "No updates."
